# BasicCAD

How I Built a Caster Using Onshape

---
## Table of Contents
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)
* [Subassembly](#subassembly)
## Base

### Description:

The first assignment is to create the caster base. I started a sketch on the top plane of a new document. I created a rectangle with the dimensions 200mm x 120mm. Then, I created a center-point circle 20mm away from both sides of the rectangle, with a diameter of 10mm. I created a linear pattern with two other circles, each 80mm apart. Then, I extended it downwards to make two rows of three circles. I extruded the rectangle without the circles 8mm. I added a hole on the orgin (60mm away from the short side and 60mm away from the long side) with a diameter of 25mm.

### Evidence
This is what the base looks like in onshape.
[click here to view the document.](https://cvilleschools.onshape.com/documents/0d70f655203ca304cb3c5b7d/w/f55603f962f6fc74f5548a68/e/41d730c570a8d75fce9f51b6)

### Image

![image of base](https://davidswanson.org/wp-content/uploads/2020/09/westhing.png)

### Reflection

When I was building this assignment it was very helpful to know the keybord shortcuts in order to build designs much faster. I used these skills when I built the base:

* sketching (shortcut **shift-s**)
* construction lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut **E**)
* linear patterns (no shortcut)

[This video has very detailed instructions that will help a lot if you are confused at all!](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4)

Remember:
* When creating a linear pattern (or other features like a mirror), make sure that "feature" is selected at the top instead of "part" if you want to create a pattern of a feature, such as the holes in the base.
* Rename all your parts and fetures to keep track of which ones are which. That will be very helpfull with complex designs.

---


## Mount

### Description

The second step in building a caster is building a mount. I created a sketch on the face of the base I built in the first assignment. I clicked the "use features" tool and selected the outside of the base and the four small circles on the left side and the large circle. Then I used the trim feature to delete the right side of the rectangle. I added a line to turn the rectangle into a square with the dimentions 120mm x 120mm. I extruded my new sketch as a new part by 8mm, and renamed it "mount". 

### Evidence

[Click here to view the document in onshape in more detail](https://cvilleschools.onshape.com/documents/f17b32973a80d2a56a647c10/w/fd2d9b519a282c3d5eb78bf3/e/87a88c2dc5a094b2cc6ccc63)

### Image

![Image of base and mount](https://davidswanson.org/wp-content/uploads/2020/09/casterforwes.png)

### Reflection

It was very easy and fast to copy the design I had built in the base and use it for the mount. You can build it seperately in it's own part studio or document, it just takes more time to build it from scratch.

[Watch this video for three ways to do this asignment](https://www.youtube.com/watch?v=BWDk4BZFXDQ&feature=emb_logo)

Remember:
* If you build the mount in the same part studio as the base, make it it's own part when you extrude it.
* If you build the mount in its own part studio, use all the keybord shortcuts above.

On this assignment I learnded how to use the trim feture (looks like scissors) and the copy feture. 

Designing stuff on Onshape is really fun!!!

---

## Fork

### Description

The third assignment is to build a fork. It has an 80mm circle, extruded 8mm, with 1mm chamfers. On one side of the circle are two prongs, and on the other side there are two circles concentric to the large circle. One is 15mm and one is 20mm. The space between them (the ring shape) is extruded 60mm. The fork prongs are made by sketching a rectangle on the large circle with the dimensions 40mm-5mm. the side of the rectangle closest to the center of the circle is 15mm away from the center, and is perpendicular to a line going from the center of the circle to the center of the rectangle. this rectangle is extruded 75mm. It is mirrored to the other side of the circle, to make two prongs. A hole is cut through both prongs with a diameter of 10mm, a distance from the center to the top of the prong of 15mm, and an equal distance to both sides of the prong. Fillets are added to the fork on the top and the bottom. There is a 15mm fillet on the top, a 1mm fillet on the sides of that fillet, and a 4mm fillet on the bottom of the forks.


### Evidence

[Click here to view the Fork in Onshape in more detail](https://cvilleschools.onshape.com/documents/f17b32973a80d2a56a647c10/w/fd2d9b519a282c3d5eb78bf3/e/6496f925bc3c30d20ddfefb3)


### Image

![Immage of the fork](https://davidswanson.org/wp-content/uploads/2020/10/wesengineering1002.png)


### Reflection

This step was relatively fast and easy for me having just done the previous two steps and the Onshape tutorials. I created this part in a new part studio of the caster document. you can add a part studio by clicking the plus sign at the bottom left side of your screen. 
You will need to use the mirror feature when building this. When using the mirror feature, remember to select “feature mirror” instead of “part mirror”. You can use the top plane to mirror the prong across. Show or hide planes by pressing "P".

When I designed this it was helpful to watch [this video.](https://www.youtube.com/watch?v=wQlTfOw8rYQ&feature=emb_logo)

It will explain everything I didn’t explain here.

---

## Tire

### Description

The fourth assignment is to create a tire. In a new part studio I started a sketch on the front plane. From the origin I created one horizontal construction line and one vertical one. Then, I sketched a trapezoid (with two of the sides horizontal) above the origin. I added the following dimensions and constraints to my sketch:
* The  left and right sides of the trapezoid are symmetric about the vertical construction line.
* The bottom side of the trapezoid is 20mm long.
* The angle from the sides of the trapezoid to the vertical construction line is 10 degrees.
* The distance from the bottom of the trapezoid past the horizontal line (make the line be a diameter) is 80mm.
* The distance from the top of the trapezoid past the horizontal line (make this a diameter as well) is 110mm.
Then, I created a 360 degree revolve with the sketch to revolve being the trapezoid and the axis being the horizontal construction line. I added fillets on the outside edges of the tire with a radius of 8mm, and I was done!

### Evidence

[Click here to view the document in Onshape](https://cvilleschools.onshape.com/documents/f17b32973a80d2a56a647c10/w/fd2d9b519a282c3d5eb78bf3/e/9236bcf81abb980c1c5eec5e)

### Image

![Tire image](https://davidswanson.org/wp-content/uploads/2020/10/casterthefriendlygadget.png)

### Reflection

Building this was fast, but required new skills. To make a dimension into a diameter, press D (keyboard shortcut) and then select the line that would be the circumference if the sketch were revolved, and select the line that would be the origin. Move your mouse down past the origin line and the dimension should double and the line should jump downwards. To make something symmetric, under constraints select symmetric and then select the axis and the pieces to make symmetric. To dimension the angle between two lines, select dimension and then select two non parallel lines. If you need more help, like always there’s a video that explains everything. [Click here](https://www.youtube.com/watch?v=ReEGioIYSus&feature=emb_logo) to watch it. I’m excited to continue building the caster. I think I’m very close to finishing.

---

## Wheel

Note: 
Building a wheel is complicated and requires lots of immages to explain how to build it, so I'm going to explain the general idea and give you some tips to use when building it, but if you want clear, detailed instructions, watch the video linked in the reflection.

### Description

Now, you have to build a wheel. In the same part studio as the tire, create a sketch and revolve it to make the wheel. You will need to add spokes by sketching another shape on the face of the wheel, extruding it to remove part of the wheel, and creating a patern to have five more sections cut out. After you add fillets, you will be done with the wheel.

### Evidence

[Click Here](https://cvilleschools.onshape.com/documents/f17b32973a80d2a56a647c10/w/fd2d9b519a282c3d5eb78bf3/e/9236bcf81abb980c1c5eec5e) to view the document on Onshape.

### Image

![Image of tire](http://davidswanson.org/wp-content/uploads/2020/10/rolling.png)

### Reflection

[This video](https://www.youtube.com/watch?v=RKeALFyqSGw&feature=emb_logo) will explain the whole design in depth.

Remember while building the wheel:
* Make sure your sketches are fully constrained and dimensioned properly so you can have a wheel of the right shape.
* Make sure you rename your parts and features to keep them organized while you design your wheel.
* Turn off the visibility of the tire while you work on the wheel.
You're almost done! This is the hardest part in the caster.

---

## AxleCollarBearings

### Description

These are the last parts you have to build before the sub-assembly and assembly. They are small and easy but important.
To start, create an axle in a new part studio. The dimensions for the axle are:
* ID 6mm
* OD 10mm
* Extrude 60mm
* flat cutout 4.5mm from the center
* flat cutout extruded 10mm, mirrored to both sides

Next, create a collar in the same part studio as the axle. The dimensions for the collar are:
* ID 10mm
* OD 15mm
* extruded 10mm
* set screw hole 3mm, centered on collar
* Hole extruded through the collar.

The dimensions for the bearing are the same as the middle two circles on the wheel, extruded 5mm.

The dimensions for the big bearing are:
* ID 20mm
* OD 30mm
* extruded 5mm

### Evidence

[Click here](https://cvilleschools.onshape.com/documents/f17b32973a80d2a56a647c10/w/fd2d9b519a282c3d5eb78bf3/e/12597fdb9dbcb6c93f6dfca5) to view the caster in onshape.

### Image

![axle and collar](https://davidswanson.org/wp-content/uploads/2020/10/drawingfromwes.png)![bigbearing](https://davidswanson.org/wp-content/uploads/2020/10/bearing.png)![bearing](https://davidswanson.org/wp-content/uploads/2020/10/wheelwes.png)

### Reflectionn

[This video](https://www.youtube.com/watch?v=2r7YqGuF1vY&feature=emb_logo) should explain the whole process in detail.

Here are some things to remember:
* Make the axle and collar separate parts
* Use the "Use" feature when creating seperate parts in the same part studio.
* When creating the set screw hole in the collar, make sure it is set to remove, and merge scope is only on for the collar, not the axle.
* Like always, rename your parts and features to stay organized.

After this, all that's left is assembling the parts!

## Subassembly

### Description
